# Generated by Django 4.1.2 on 2022-11-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('work_status', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='')),
                ('image', models.ImageField(default='abc.jpg', upload_to='Images')),
                ('gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('resume_headline', models.CharField(default='It is the first thing recruiters notice in your profile. Write concisely what makes you unique and right person for the job you are looking for', max_length=20)),
                ('key_skills', models.CharField(default='Tell recruiters what you know or what you are known for e.g. Direct Marketing, Oracle, Java etc. We will send you job recommendations based on these skills. Each skillis separated by a comma.', max_length=40)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=25)),
                ('university', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=20)),
                ('marks', models.FloatField(default=35)),
                ('year', models.DateField()),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userinfo')),
            ],
            options={
                'db_table': 'UserEducation',
            },
        ),
        migrations.CreateModel(
            name='UEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('Join_date', models.DateField()),
                ('salary', models.FloatField(default=0)),
                ('profile', models.CharField(max_length=30)),
                ('notice_period', models.CharField(max_length=20)),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userinfo')),
            ],
            options={
                'db_table': 'UEmployment',
            },
        ),
    ]
