# Generated by Django 4.1.2 on 2022-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_usereducation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(default='abc.jpg', upload_to=''),
        ),
    ]
