# Generated by Django 4.1.2 on 2022-11-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_userinfo_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='resume_headline',
            field=models.CharField(max_length=20),
        ),
    ]
