# Generated by Django 4.1.2 on 2022-11-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_alter_userinfo_resume_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='key_skills',
            field=models.CharField(max_length=40),
        ),
    ]
