# Generated by Django 4.1.2 on 2022-12-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_indusrty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indusrty',
        ),
    ]
