# Generated by Django 4.1.2 on 2022-12-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='type',
            field=models.CharField(max_length=35),
        ),
    ]
