# Generated by Django 4.1.2 on 2022-12-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_alter_industry_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
