# Generated by Django 4.1.2 on 2022-12-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0015_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
