# Generated by Django 4.1.2 on 2022-12-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0017_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
