# Generated by Django 4.1.2 on 2022-12-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0021_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
