# Generated by Django 4.1.2 on 2022-12-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0023_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateField(default='django.utils.timezone.now'),
        ),
    ]
