# Generated by Django 4.1.2 on 2022-12-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0025_alter_company_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(max_length=10),
        ),
    ]
