# Generated by Django 4.1.2 on 2022-12-02 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0026_alter_company_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='DOB',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
