# Generated by Django 4.1.2 on 2022-12-05 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0027_alter_userinfo_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uemployment',
            name='Join_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=20)),
                ('salary', models.FloatField(default=100)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('skills', models.CharField(max_length=30)),
                ('no_opening', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.company')),
            ],
            options={
                'db_table': 'Job',
            },
        ),
    ]
