# Generated by Django 4.1.2 on 2022-12-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0028_alter_uemployment_join_date_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
