# Generated by Django 4.1.2 on 2022-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0031_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='post',
            field=models.IntegerField(default=100),
        ),
    ]
