# Generated by Django 4.1.2 on 2022-12-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0032_alter_company_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
