# Generated by Django 4.1.2 on 2022-12-07 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0033_remove_job_company_delete_company_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('phone', models.IntegerField()),
                ('person', models.CharField(max_length=25)),
                ('pincode', models.IntegerField()),
                ('address1', models.CharField(max_length=25)),
                ('image1', models.ImageField(default='abc.jpg', upload_to='Images')),
                ('password', models.CharField(max_length=25)),
                ('plan', models.CharField(max_length=15)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('post', models.IntegerField(default=100)),
                ('expiry_date', models.DateField(default=datetime.datetime.now)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.industry')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=20)),
                ('salary', models.FloatField(default=100)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('skills', models.CharField(max_length=30)),
                ('no_opening', models.IntegerField()),
                ('Education', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.company')),
            ],
            options={
                'db_table': 'Job',
            },
        ),
    ]
