# Generated by Django 4.1.2 on 2022-12-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0035_alter_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
    ]
