# Generated by Django 4.1.2 on 2022-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0036_remove_job_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='Not Disclosed', max_length=20),
        ),
    ]
