# Generated by Django 4.1.2 on 2022-12-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0039_alter_company_image1_alter_userinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image1',
            field=models.ImageField(default='abc.jpg', upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='abc.jpg', upload_to='Images'),
        ),
    ]
