# Generated by Django 4.1.2 on 2022-12-16 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0040_alter_company_image1_alter_userinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='response',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='APPLY', max_length=10)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.job')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userinfo')),
            ],
            options={
                'db_table': 'Apply',
            },
        ),
    ]
