# Generated by Django 4.1.2 on 2022-12-17 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0041_job_response_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('msg', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.job')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userinfo')),
            ],
            options={
                'db_table': 'Msg',
            },
        ),
    ]
